### ISSUE TITLE
ARM Dockerfile

### ISSUE THREAD

**Issue by ianhundere** [zeppelinux/ninjam-helm#1]
hey hey!

thanks for all your hard work on this. i recently started playing with ninjam and have wanted to host my own server w/ persistent storage. i currently have a 4 node rpi cluster running k3s and wanted to try deploying your dockerfile, but noticed it's not compiled for arm. 

if this is something i can do, i'll do it and create a PR. 

lemme know how i can help :o)

**Comment by zeppelinux** [comment]
Hi there!

my rpi 400 melted in a house fire last this Tuesday  (everybody are save), so I don’t have  access to rpi build runtime anymore.  You can check out/clone the repo https://github.com/zeppelinux/ninjam and try to build it on yours. Verify ninjas works.
Hopefully there is rpi target platform available in the GitHub and both builds (Linux and rpi) can be triggered automatically on the tag push. Let me know how it goes. Good luck!

**Comment by ianhundere** [comment]
oh man, that's terrible. i'm sorry to hear, but relieved to hear everyone is okay.

i'll keep investigating and see what i need to do to get'r done.

take care / best of luck 

edit: managed to compile it locally and it runs fine.

**Comment by ianhundere** [comment]
```
jobs:
  multi:        
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: |
            user/app:latest
            user/app:1.0.0        
```

i'm not super familiar with github actions, but it looks as if this is all that would be needed to build it for raspberry pi.
